### ISSUE TITLE
[Bug] Footway showing as extruded

### ISSUE THREAD

**Issue by PuzzleHeadedTable** [open-indoor/openindoor6#14]
footway is extruded

https://app.openindoor.io/#19.63/-1.6998229/48.1194799/60.00/-115.20

<img width="1268" alt="Capture d’écran 2021-11-19 à 10 55 27" src="https://user-images.githubusercontent.com/94530860/142603660-ec1fb330-61bf-42d0-973c-eebf390afecb.png">

**Comment by cigone-openindoor** [comment]
<img width="1436" alt="Screenshot 2021-11-21 at 17 55 58" src="https://user-images.githubusercontent.com/69067574/142771499-fb4f5e1a-7f42-4272-a014-918e1fb64983.png">
Fix for overpass data (not validated for dragNdropped geojson).
