### ISSUE TITLE
Please, stop spamming

### ISSUE THREAD

**Issue by matkoniecz** [open-indoor/openindoor6#20]
I received spam from someone claiming to represent https://github.com/open-indoor/openindoor6/

Apparently all people on https://github.com/tordanik/OSM2World/graphs/contributors list were spammed given what kind of contributions I made ( https://github.com/tordanik/OSM2World/commits?author=matkoniecz ).

```
Hi Mateusz, how are you ? 

I saw on Github you contributed to Osm2World, good job !

I am contacting you to let you know that I’m working on an open source web app aiming to provide a 3D rendering of building interior mapping based ,among other things, on OSM data. 

Given the work you have done on Osm2World, I thought you could give us some valuable feedback on our project. 

Our project : https://app.openindoor.io <https://app.openindoor.io/> (work in progress)

Our Github : https://github.com/open-indoor/openindoor6 <https://github.com/open-indoor/openindoor6>

Our Slack channel : https://osmus.slack.com/archives/C02N7ARHUBS <https://osmus.slack.com/archives/C02N7ARHUBS>

Our Discord channel : https://discord.gg/KccurGvG7F <https://discord.gg/KccurGvG7F>

I’m looking forward to hearing from you soon, 

Cheers. 

Fred
```

I never received email from that person, I do not recognize that person, I have not signed up for receiving emails about all OSM projects.

This is unwanted spam, please do not this.

I marked this email as spam and I hope that this account / domain will be appropriately marked as spammers.

To notify OSM Community please use for example OSM Weekly or mention your project in other contact channels as appropriate.

Rather than spamming all people who ever contributed to some project. It gets tiresome and I get such spam quite often.

**Comment by matkoniecz** [comment]
To be more clear - partial reason for posting this is explicit request

> I thought you could give us some valuable feedback on our project

I am not suffering from lack of ideas for things to do (even after limiting to open source OSM projects) so unsolicited emails about unpaid work are not appreciated.

I would be quite likely to give feedback about project itself if I would learn about it from OSM World Discord channel or from OSM Weekly.

**Comment by matkoniecz** [comment]
Obviously, if maintainers of this project are unrelated to this spam then there is nothing that you could really do.

**Comment by cigone-openindoor** [comment]
Hi Mateusz,

So I reply openly to your open messages.

We are a very little company, starting from scratch.

Before doing any business (if any), we try to inform people who could be interested that we work also on hard coding task for OSM and new features.

We are strongly invested in open source projects. All what we code is open source, and we try to provide the best of what we do.
Some members of the team are not coders and do not know well the common habits of dev world.

So, big apologize about disturbance.

We did not want to spam you at all, but only inform you about our initiative that could have interest you.

Best regards,

Clement IGONET
OpenIndoor CEO

**Comment by matkoniecz** [comment]
> We did not want to spam you at all, but only inform you about our initiative that could have interest you.

Most of spam is to inform "about our initiative that could have interest you"
