### ISSUE TITLE
Add controls for rotations (pitch, bearing)

### ISSUE THREAD

**Issue by cigone-openindoor** [open-indoor/openindoor6#3]
To simplify camera rotations, some controls would be welcome (other than right mouse button, or CTRL + left mouse button)

**Comment by 1ec5** [comment]
Dragging on the ↕️ button seems to already adjust both the pitch and the bearing.

**Comment by cigone-openindoor** [comment]
Not false.
So, we close the issue.
It's a basic maplibre feature.
