### ISSUE TITLE
[BUG] Infinite loading.

### ISSUE THREAD

**Issue by CoderThomasB** [open-indoor/openindoor6#32]
When I try to view the contents of this building it just gets stuck in an infinite loading screen; Can anyone help with this issue?

Link:[https://app.openindoor.io/#20.14/-43.5361106/172.6359815/0/54](https://app.openindoor.io/#20.14/-43.5361106/172.6359815/0/54)

**Comment by cigone-openindoor** [comment]
OK, just fixed.
Thanks for feedback.
