### ISSUE TITLE
What do the colors refer to (if anything)?

### ISSUE THREAD

**Issue by JesseWeinstein** [open-indoor/openindoor6#6]
The bright primary colors are very entertaining, but it's confusing if they are just to distinguish buildings and levels, of if they have more specific meanings.

**Comment by PuzzleHeadedTable** [comment]
![proposition pictos et couleurs](https://user-images.githubusercontent.com/94530860/142189311-647a009f-0c51-4f7d-b079-6b0464abf483.png)

Here's a proposition for the colors
