### ISSUE TITLE
[bug] levels undefined

### ISSUE THREAD

**Issue by cigone-openindoor** [open-indoor/openindoor6#7]
To reproduce:
- https://app-dev.openindoor.io/#19.95/-1.7023445/48.1199607/60.00/46.85
- https://app.openindoor.io/#14.26/-85.76008535/38.2583666/60.00/0.00
TODO: unblock the case.

**Comment by cigone-openindoor** [comment]
fixed and tested

**Comment by yomexelect** [comment]
There is an issue with level rendering on Hartford building. Please check this link: https://app.openindoor.io/#19.77/-85.7528192/38.2466866/60.00/0.00

**Comment by yomexelect** [comment]
I tried the drag and Drop feature on the app but it didn't work.

**Comment by cigone-openindoor** [comment]
Is it data you would accept to share to let us have a try ?

**Comment by cigone-openindoor** [comment]
<img width="752" alt="Screenshot 2021-12-03 at 10 15 10" src="https://user-images.githubusercontent.com/69067574/144577117-fe50fa05-9296-4054-a7f7-6fbd43d33895.png">

<img width="752" alt="Screenshot 2021-12-03 at 10 15 42" src="https://user-images.githubusercontent.com/69067574/144577206-b8cd6528-474d-42a1-a425-68054d85c2df.png">
