### ISSUE TITLE
mall doesn't look great

### ISSUE THREAD

**Issue by cigone-openindoor** [open-indoor/openindoor6#9]
"
Here's an example of a mall, well mapped by @westnordost, that doesn't look great in OpenIndoor (yet): https://app.openindoor.io/#16.22/9.9956841/53.5517728/41.81/0.00
"

![image](https://user-images.githubusercontent.com/69067574/142611679-0ae66ee6-9979-4de8-b05d-ebd98eed66be.png)

This other example: https://app.openindoor.io/#20.00/-84.4646292/39.2904852/47.50/-176.00
![image](https://user-images.githubusercontent.com/69067574/142611379-155bf7a2-5ae2-45f4-a183-610b197189ca.png)

**Comment by westnordost** [comment]
East of it is the central station. It is a very complex indoor-area with a lot of areas on top or below each other, might want to check this out too. Both render finde on indoor=, OpenLevelUp etc.

**Comment by cigone-openindoor** [comment]
Maybe a matter of updated data.
We are working on it...

**Comment by cigone-openindoor** [comment]
What you think about last version ?
<img width="944" alt="Screenshot 2021-12-03 at 10 09 49" src="https://user-images.githubusercontent.com/69067574/144576271-228ff941-6bca-4bed-8f0d-b28685b9c0d4.png">
?
